export const elements = {
  menu: document.querySelectorAll('.menu-icon'),
  canvas: document.querySelector('#off-canvas'),
  noGpView: document.querySelector('#no-gp-yet'),
  showCalcArea: document.querySelector('#showCalcArea'),
  calcArea: document.querySelector('#calcArea') ,
  addGpRowBtn: document.querySelector('#addGpRow'),
  gpCalcUl: document.querySelector('#gpCalcUl'),
  gpDisplayInput: document.querySelector('#gpa-display #gpaId'),
  gpDisplay: document.querySelector('#gpa-display h1'),
  gpDisplayP: document.querySelector('#gpa-display p'),
  showSaveGpPopBtn: document.querySelector('#saveGpBtn'),
  savePopup: document.querySelector('#save-popup'),
  saveGp: document.querySelector('#save-btn'),
  gpNameInput: document.querySelector('#gpName'),
  showSavedGp: document.querySelector('#show-saved-gp'),
  showSavedGpBtn: document.querySelector('#showSavedGpBtn'),
  gpShowUl: document.querySelector('#gpShowUl'),
  showCalcAreaBtn: document.querySelector('#showCalcAreaBtn'),
  closePop: document.querySelectorAll('.close-pop'),
  searchInput: document.querySelector('#search'),
  editArea: document.querySelector('#editArea'),
  gpEditUl: document.querySelector('#gpEditUl'),
  addGpRowEdit: document.querySelector('#addGpRowEdit'),
  showUpdateGpPopBtn: document.querySelector('#updateGpBtn'),
  updatePopup: document.querySelector('#update-popup'),
  gpEditNameInput: document.querySelector('#gpEditName'),
  updateGp: document.querySelector('#update-btn')
}